tgpage_page_category:
  type: string
  default: ""
  description: 
    en: 'Enter the category slug of your content page category as it appears in the url. 
        The slug is bold in the following example url: 
        https://community.example.org/c/<b>blog-posts</b>
        <br><br>
        Note: you may use more than one category slug by comma separating the
        slug values like: <b>blog-one,blog-two</b> <br>
        Be sure there are no spaces after the commas.'
tgblog_blog_category:
  type: string
  default: ""
  description: 
    en: 'Enter the category slug of your blog category as it appears in the url. 
        The slug is bold in the following example url: 
        https://community.example.org/c/<b>blog-posts</b>
        <br><br>
        Note: you may use more than one category slug by comma separating the
        slug values like: <b>blog-one,blog-two</b> <br>
        Be sure there are no spaces after the commas.'
tgblog_image_display_style:
  type: enum
  default: "responsive crop"
  choices:
    - responsive crop
    - center fit
  description:
    en: 'Responsive Crop - always display at 100% width, evenly cropping the image as needed.
        <br>
        Center Fit - display the full image, maintaining the aspect ratio and centering it within the page.'
tgblog_mobile_enabled:
  type: bool
  default: false
  description:
    en: 'BETA VERSION - please provide feedback in the theme component topic.'
tgblog_no_images:
  type: bool
  default: false
  description:
      en: 'Enable if you want to include the styling without images at the top.'
tgblog_full_width:
  type: bool
  default: false
  description:
    en: (EXPERIMENTAL) Display the blog post in a full-width format on desktop.